# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Twitter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Twitter
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'
  pod 'FirebaseCore'
  pod 'SDWebImage', '~> 5.0'
  pod 'ActiveLabel'

end
